permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name: 王梓
  email: wangzi6147@gmail.com
  link: http://wangzi6147.github.io
  weibo: http://weibo.com/u/1570037995
  github: http://github.com/wangzi6147
 # music: http://site.douban.com/linanya
 # linkedin: https://www.linkedin.com/pub/anya-lin/81/91/232

# 站点信息
title: 王梓的博客
description: My personal blog
url: http://wangzi6147.github.io
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/guitar.png
favicon: /public/img/guitar.png

# google analytics 设置
#ga:
#  id: UA-54262064-1 
#  url: painterlin.com

# disqus 设置
disqus:
  shortname: wangzi6147

# duoshu 设置
duoshuo:
  shortname: wangzi6147
  
# 主题设置，自动激活某个标签
active: 技术

# 首页除了最新文章外显示分类
#cates: 
#  - 矩阵补全
#  - LaTeX

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档